### PR TITLE
Upgrade restler to version 3.2.2

### PR DESCRIPTION
**Pull request by kblok**
A test called "It is able to chain several calls" was added which proves that with the previous version of restler the module fails when chaining several calls due to a memory leak (see: https://github.com/danwrong/restler/pull/113 and https://github.com/danwrong/restler/issues/129)

This test needs a config.js file in the test folder with a trello configuration, that's why this test is ignored by default (".skip"). This file should contain something like this:

```javascript
module.exports = {
    key: "some valid key",
    token: "some valid token",
    listId: "some valid listId"
};
```

### CODE REVIEW

**Comment by noamokman** [comment]
Why is this not being merged?

**Comment by kblok** [comment]
I don't know @noamokman. I've got no comments...

**Comment by noamokman** [comment]
Out of all trello packages, this is the most maintained, and yet it isn't.. what can we do?

**Comment by GraemeF** [comment]
Hi guys, @devtyr is maintaining this module now and merged your last pr - maybe he is busy at the moment.

**Comment by masonforest** [comment]
@devtyr are you still maintaining this module? I'd be happy to take over if you're busy or lost interested. Thanks guys!

**Comment by sinisterstuf** [comment]
I'm also eagerly awaiting this merge :+1: There's also a newer restler out in the meantime: 3.3.0 [NPM Version](https://www.npmjs.com/package/restler)

**Comment by norberteder** [comment]
@masonforest Sorry, I migrated @devtyr to an organization and rights got lost. Everything fixed now.

**Pull request merged**
