### PR TITLE
Added option to return a Promise.

### PR DESCRIPTION
**Pull request by seanmadden**
I was working with this library and saw myself getting stuck in callback hell. I decided to modify it to return a promise if no callback is provided. This should be a backwards compatible change, and all the previous tests pass.

I also added two tests to ensure promises were being returned when expected.

This request should probably be rejected if you don't want to force ES6 compatibility as it uses ES6 promises (though it works with node 4.1.0).

Suggestions welcome if you can see how I can make this change better. It feels a bit weird to me for makeRequest to return a promise or undefined, but I couldn't think of a cleaner way to do

### CODE REVIEW

**Comment by rosshinkley** [comment]
+1 for adding promise support.  

@seanmadden If you're interested in not enforcing ES6 or harmony, you may want to consider taking a look at integrating something like [bluebird](https://github.com/petkaantonov/bluebird) as a dependency.

**Comment by seanmadden** [comment]
@rosshinkley for my purposes, ES6 promises are great since I intended to work on node version > 4. It looks like node > 0.11 has ES6 promise support as well, so I probably won't go back and implement bluebird promises.

**Comment by rosshinkley** [comment]
@seanmadden for sure, and for my purposes, native promises also work nicely.   I just wanted to float the idea. :)

Thinking out loud, I suppose it depends on what versions of node this library is to support, and as such, maybe the package and/or the readme should also be updated.  Thoughts?

**Comment by seanmadden** [comment]
I think that's a good idea. I'd like to hear what the maintainer of this repo thinks, too. @norberteder ?

**Comment by norberteder** [comment]
I like the idea to return a promise in general and I will have a look at it.

Before, can you please fix the build? :)

**Comment by seanmadden** [comment]
Build is broken because Node < 0.10 doesn't support ES6 Promise. The build is passing on node > 0.10

**Comment by rosshinkley** [comment]
Again pondering out loud, you could also use an [ES6 polyfill](https://github.com/jakearchibald/es6-promise).  The only material change you'd have to make to the PR is patching global with the polyfill method:

```javascript
require('es6-promise').polyfill();
```

That would let this library work with or without harmony and across multiple versions of node, including <0.10.
.

**Comment by seanmadden** [comment]
That's probably a good option for this... I'll look into it when I get home later today.

**Comment by seanmadden** [comment]
It appears polyfill has done the trick

**Comment by rosshinkley** [comment]
No problem.  I'm happy that helped.  I don't suppose I could +1 again? ;)

**Comment by seanmadden** [comment]
@norberteder Can you take a look now that I've polyfilled Promise for Node < 0.11?

**Comment by norberteder** [comment]
Thank you very much for your contribution!

**Pull request merged**
